# https://toml.io/en/
site_title = "BitPacking" # 无事牌
site_url = "https://blog.xiayf.cn/"
site_desc = "精进，求诸己身"
site_ico = "/assets/bits_small.ico"

exclude_source_entries = ["node_modules", "config.toml", "package.json", "package-lock.json"]
dist_dir = "../dist/blog"

theme_dir = "../../themes"
theme_name = "default"

navigation = [["关于我", "/pages/about.html"], ["作品", "/pages/works.html"], ["RSS", "/rss.xml"]]

plugins = ["PlantUML", "Mermaid", "TypstCmarkerPdf"]

[plantuml]
server = "127.0.0.1:8000"
header = "skinparam defaultFontName \"Albert Sans\"\nskinparam defaultFontSize 15\nscale max 1600 width"
jar_path = "/Users/xiayf/software/plantuml-mit-1.2025.1.jar"

[typst_pdf]
output_dir = "../dist/blog/pdf"
text_fonts = "\"Zhuque Fangsong (technical preview)\", \"TsangerJinKai05 W04\""

[small_image]
thresold = 1048576 # 1MB