# https://toml.io/en/
site_title = "BitPacking" # 道场
site_url = "https://blog.xiayf.cn/"
site_desc = "精进，求诸己身"
site_ico = "/assets/bits_small.ico"

exclude_source_entries = ["node_modules", "config.toml", "package.json", "package-lock.json"]
dist_dir = "../dist/blog"

theme_dir = "../../themes"
theme_name = "default"

navigation = [["关于我", "/pages/about.html"], ["作品", "/pages/works.html"], ["琳琅", "/pages/linlang.html"], ["RSS", "/rss.xml"]]

plugins = ["PlantUML", "Smms", "Giscus", "Highlight", "Mathjax"]

[plantuml]
#server = "127.0.0.1:8000"
header = "skinparam defaultFontName \"Albert Sans\"\nskinparam defaultFontSize 15\nscale max 800 width"
jar_path = "/Users/xiayf/software/plantuml-mit-1.2025.1.jar"
picoweb_port = 8000

[typst_pdf]
output_dir = "../dist/blog/pdf"
text_fonts = "\"Zhuque Fangsong (technical preview)\", \"TsangerJinKai05 W04\""

[smms]
username = "xiayf"
password = "06122553abc"
api_token = ""

[giscus]
enable = true
repo = "kitelife/kitelife.github.com"
repo_id = "MDEwOlJlcG9zaXRvcnk4NTg1Njcx"
category = "giscus"
category_id = "DIC_kwDOAIMBx84Ctgkx"

[storage]
db_file_path = "../dist/ling.db"
init_sql = [
    "CREATE TABLE IF NOT EXISTS access_log (id INTEGER PRIMARY KEY AUTOINCREMENT, peer TEXT, http_action TEXT, query_path TEXT, user_agent TEXT, created_time TEXT)",
    "CREATE TABLE IF NOT EXISTS rss_subscription (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, url TEXT, tag TEXT, updated_time TEXT)",
    "CREATE TABLE IF NOT EXISTS rss_item (id INTEGER PRIMARY KEY AUTOINCREMENT, subscription_id INTEGER, title TEXT, url TEXT, content TEXT, has_read INTEGER, updated_time TEXT)"
]