# https://toml.io/en/
site_title = "BitPacking" # 无事牌
site_url = "https://blog.xiayf.cn/"
site_desc = "精进，求诸己身"

theme_dir = "../../themes"
theme_name = "default"

navigation = [["关于我", "/pages/about.html"], ["作品", "/pages/works.html"], ["RSS", "/rss.xml"]]

plugins = ["plantuml", "mermaid"]

[plantuml]
server = "127.0.0.1:8000"
header = "skinparam defaultFontName \"Albert Sans\"\nskinparam defaultFontSize 15\nscale max 1600 width"
jar_path = "/Users/xiayf/software/plantuml-mit-1.2025.1.jar"