name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: git submodule
      run: git submodule update --init --recursive
    - name: install conan
      run: pip install conan
    - name: conan profile
      run: conan profile detect
    - name: conan dep
      run: conan install . --build=missing
    - name: cmake present conan
      run: cmake --preset conan-release
    - name: cmake build
      run: cmake --build --preset conan-release

  build-on-ubuntu:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: git submodule
      run: git submodule update --init --recursive
    - name: Install package
      run: |
          sudo apt-get update
          sudo apt-get -y install cmake clang openssl libssl-dev
          which clang
          which clang++
          which cmake
          pip install conan
          which conan
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
    - name: conan profile
      run: conan profile detect
    - name: conan dep
      run: conan install . --build=missing
    - name: cmake present conan
      run: cmake --preset conan-release
    - name: cmake build
      run: cmake --build --preset conan-release
