name: Ubuntu C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: git submodule
        run: git submodule update --init --recursive
      - name: env check and install dep
        run: |
          which clang
          clang --version
          which clang++
          clang++ --version
          which cmake
          sudo apt-get install libc++-dev libc++abi-dev
          pip install conan
          which conan
      - name: conan profile
        run: |
          conan profile detect
          cp linux-clang-conan-profile ~/.conan2/profiles/clang
          tree ~/.conan2/profiles
      - name: conan dep
        run: conan install . --profile=clang --build=missing
      - name: cmake present conan
        run: cmake --preset conan-release
      - name: cmake build
        run: cmake --build --preset conan-release
      - name: ctest
        run: sh ./run_test.sh